version = 5.2.2
archive_dir = /etc/letsencrypt/archive/kcbtestserver.cloud
cert = /etc/letsencrypt/live/kcbtestserver.cloud/cert.pem
privkey = /etc/letsencrypt/live/kcbtestserver.cloud/privkey.pem
chain = /etc/letsencrypt/live/kcbtestserver.cloud/chain.pem
fullchain = /etc/letsencrypt/live/kcbtestserver.cloud/fullchain.pem
[renewalparams]
account = 8908ae77bc34ffd857a09b68ef7a9fec
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
kcbtestserver.cloud = /var/www/certbot
